### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by colt05-usr** [jadaradix/dsgamemaker#2]
Hello!
DSGM will not let me add more than 10 objects because the server is down. Is there a workaround?
Thanks.

**Comment by colt05-usr** [comment]
NVM. The download link is at [a website backup](http://jadaradix.com/sites/dsgamemaker.com/downloads/Install520.exe)

**Comment by colt05-usr** [comment]
5.20 also crashes

**Comment by jadaradix** [comment]
Thanks for bringing this up. I will try to make a release which doesn't talk to dsgamemaker.com whatsoever.

**Comment by colt05-usr** [comment]
Thanks!

**Comment by colt05-usr** [comment]
Nvm https://github.com/colt05/dsgamemaker fixed some of the problems 5.20 has

**Comment by colt05-usr** [comment]
Where did the website go? I remember there was one hosted on jada.io?

**Comment by jadaradix** [comment]
I still have the website files but it's not source code I want to make public (it's 10 year old PHP).
